# Generated by Django 4.1.5 on 2023-06-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0004_salesitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='valid_to',
            field=models.DateTimeField(null=True),
        ),
    ]
