# Generated by Django 4.1.5 on 2023-06-07 22:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0006_remove_sales_valid_to_products_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
